apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels: 
    app: webapp
spec: 
  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template: 
    metadata:
      labels:
        app: webapp
    spec: 
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"