apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass 
        - name: MYSQL_DATABASE
          value: fleetman
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  type: ClusterIP

